global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-prometheus-exporter.web.svc.cluster.local:9113"]

  - job_name: "opensearch"
    static_configs:
      - targets: ["opensearch.web.svc.cluster.local:9200"]
    metrics_path: "/_prometheus/metrics"

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana.monitoring.svc.cluster.local:3000"]
    metrics_path: "/metrics"
